// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Pause():Promise<string>;

export function Resume():Promise<string>;

export function SkipBack():Promise<string>;

export function SkipForward():Promise<string>;

export function Toggle():Promise<string>;
