// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function JumpToCheckpoint(arg1) {
  return window['go']['rsvp']['RsvpService']['JumpToCheckpoint'](arg1);
}

export function JumpToEnd() {
  return window['go']['rsvp']['RsvpService']['JumpToEnd']();
}

export function JumpToStart() {
  return window['go']['rsvp']['RsvpService']['JumpToStart']();
}

export function OnDomReady(arg1) {
  return window['go']['rsvp']['RsvpService']['OnDomReady'](arg1);
}

export function OnShutdown(arg1) {
  return window['go']['rsvp']['RsvpService']['OnShutdown'](arg1);
}

export function OnStartup(arg1) {
  return window['go']['rsvp']['RsvpService']['OnStartup'](arg1);
}

export function SkipBackward() {
  return window['go']['rsvp']['RsvpService']['SkipBackward']();
}

export function SkipFoward() {
  return window['go']['rsvp']['RsvpService']['SkipFoward']();
}

export function StreamNodes(arg1) {
  return window['go']['rsvp']['RsvpService']['StreamNodes'](arg1);
}
