// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Pause() {
  return window['go']['rsvp']['Rsvp']['Pause']();
}

export function Resume() {
  return window['go']['rsvp']['Rsvp']['Resume']();
}

export function SkipBack() {
  return window['go']['rsvp']['Rsvp']['SkipBack']();
}

export function SkipForward() {
  return window['go']['rsvp']['Rsvp']['SkipForward']();
}

export function Toggle() {
  return window['go']['rsvp']['Rsvp']['Toggle']();
}
