// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function JumpToCheckpoint(arg1:number):Promise<void>;

export function JumpToEnd():Promise<void>;

export function JumpToStart():Promise<void>;

export function OnDomReady(arg1:context.Context):Promise<void>;

export function OnShutdown(arg1:context.Context):Promise<void>;

export function OnStartup(arg1:context.Context):Promise<void>;

export function SkipBackward():Promise<void>;

export function SkipFoward():Promise<void>;

export function StreamNodes(arg1:string):Promise<any|any>;
