#!/bin/bash

find . \
    \( \
    -name bun.lockb \
    -o -name .svelte-kit \
    -o -name 'vite.config.ts.*' \
    -o -type d -name node_modules \
    -o -name d -name cache \
    -o -name d -name tmp \
    -o -name d -name logs \
    -o -type d -name build \
    -o -type d -name dist \
    -o -type d -name wailsjs \
    \) \
    -exec rm -rf {} +

echo "✅ Pruned autogenerated files and directories."
